/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.t2p5.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T2P5Entry service. Represents a row in the &quot;T2P5_T2P5Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.acme.t2p5.model.impl.T2P5EntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.acme.t2p5.model.impl.T2P5EntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T2P5Entry
 * @generated
 */
@ProviderType
public interface T2P5EntryModel extends BaseModel<T2P5Entry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t2p5 entry model instance should use the {@link T2P5Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this t2p5 entry.
	 *
	 * @return the primary key of this t2p5 entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t2p5 entry.
	 *
	 * @param primaryKey the primary key of this t2p5 entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the t2p5 entry ID of this t2p5 entry.
	 *
	 * @return the t2p5 entry ID of this t2p5 entry
	 */
	public long getT2p5EntryId();

	/**
	 * Sets the t2p5 entry ID of this t2p5 entry.
	 *
	 * @param t2p5EntryId the t2p5 entry ID of this t2p5 entry
	 */
	public void setT2p5EntryId(long t2p5EntryId);

	/**
	 * Returns the description of this t2p5 entry.
	 *
	 * @return the description of this t2p5 entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this t2p5 entry.
	 *
	 * @param description the description of this t2p5 entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this t2p5 entry.
	 *
	 * @return the name of this t2p5 entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this t2p5 entry.
	 *
	 * @param name the name of this t2p5 entry
	 */
	public void setName(String name);

}