/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.e4g5.model.impl;

import com.acme.e4g5.model.E4G5Entry;
import com.acme.e4g5.model.E4G5EntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the E4G5Entry service. Represents a row in the &quot;E4G5_E4G5Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>E4G5EntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link E4G5EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see E4G5EntryImpl
 * @generated
 */
public class E4G5EntryModelImpl
	extends BaseModelImpl<E4G5Entry> implements E4G5EntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e4g5 entry model instance should use the <code>E4G5Entry</code> interface instead.
	 */
	public static final String TABLE_NAME = "E4G5_E4G5Entry";

	public static final Object[][] TABLE_COLUMNS = {
		{"e4g5EntryId", Types.BIGINT}, {"description", Types.VARCHAR},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("e4g5EntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table E4G5_E4G5Entry (e4g5EntryId LONG not null primary key,description VARCHAR(75) null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table E4G5_E4G5Entry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY e4g5Entry.e4g5EntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY E4G5_E4G5Entry.e4g5EntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long E4G5ENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public E4G5EntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _e4g5EntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setE4g5EntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _e4g5EntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return E4G5Entry.class;
	}

	@Override
	public String getModelClassName() {
		return E4G5Entry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<E4G5Entry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<E4G5Entry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<E4G5Entry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((E4G5Entry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<E4G5Entry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<E4G5Entry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(E4G5Entry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<E4G5Entry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<E4G5Entry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, E4G5Entry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			E4G5Entry.class.getClassLoader(), E4G5Entry.class,
			ModelWrapper.class);

		try {
			Constructor<E4G5Entry> constructor =
				(Constructor<E4G5Entry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<E4G5Entry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<E4G5Entry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<E4G5Entry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<E4G5Entry, Object>>();
		Map<String, BiConsumer<E4G5Entry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<E4G5Entry, ?>>();

		attributeGetterFunctions.put("e4g5EntryId", E4G5Entry::getE4g5EntryId);
		attributeSetterBiConsumers.put(
			"e4g5EntryId",
			(BiConsumer<E4G5Entry, Long>)E4G5Entry::setE4g5EntryId);
		attributeGetterFunctions.put("description", E4G5Entry::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<E4G5Entry, String>)E4G5Entry::setDescription);
		attributeGetterFunctions.put("name", E4G5Entry::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<E4G5Entry, String>)E4G5Entry::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getE4g5EntryId() {
		return _e4g5EntryId;
	}

	@Override
	public void setE4g5EntryId(long e4g5EntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_e4g5EntryId = e4g5EntryId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, E4G5Entry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public E4G5Entry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, E4G5Entry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		E4G5EntryImpl e4g5EntryImpl = new E4G5EntryImpl();

		e4g5EntryImpl.setE4g5EntryId(getE4g5EntryId());
		e4g5EntryImpl.setDescription(getDescription());
		e4g5EntryImpl.setName(getName());

		e4g5EntryImpl.resetOriginalValues();

		return e4g5EntryImpl;
	}

	@Override
	public E4G5Entry cloneWithOriginalValues() {
		E4G5EntryImpl e4g5EntryImpl = new E4G5EntryImpl();

		e4g5EntryImpl.setE4g5EntryId(
			this.<Long>getColumnOriginalValue("e4g5EntryId"));
		e4g5EntryImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		e4g5EntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return e4g5EntryImpl;
	}

	@Override
	public int compareTo(E4G5Entry e4g5Entry) {
		long primaryKey = e4g5Entry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof E4G5Entry)) {
			return false;
		}

		E4G5Entry e4g5Entry = (E4G5Entry)object;

		long primaryKey = e4g5Entry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<E4G5Entry> toCacheModel() {
		E4G5EntryCacheModel e4g5EntryCacheModel = new E4G5EntryCacheModel();

		e4g5EntryCacheModel.e4g5EntryId = getE4g5EntryId();

		e4g5EntryCacheModel.description = getDescription();

		String description = e4g5EntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			e4g5EntryCacheModel.description = null;
		}

		e4g5EntryCacheModel.name = getName();

		String name = e4g5EntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			e4g5EntryCacheModel.name = null;
		}

		return e4g5EntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<E4G5Entry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<E4G5Entry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<E4G5Entry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((E4G5Entry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<E4G5Entry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<E4G5Entry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<E4G5Entry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((E4G5Entry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, E4G5Entry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _e4g5EntryId;
	private String _description;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<E4G5Entry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((E4G5Entry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("e4g5EntryId", _e4g5EntryId);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("e4g5EntryId", 1L);

		columnBitmasks.put("description", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private E4G5Entry _escapedModel;

}