/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.j7z3.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the J7Z3Entry service. Represents a row in the &quot;J7Z3_J7Z3Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.acme.j7z3.model.impl.J7Z3EntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.acme.j7z3.model.impl.J7Z3EntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see J7Z3Entry
 * @generated
 */
@ProviderType
public interface J7Z3EntryModel extends BaseModel<J7Z3Entry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a j7z3 entry model instance should use the {@link J7Z3Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this j7z3 entry.
	 *
	 * @return the primary key of this j7z3 entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this j7z3 entry.
	 *
	 * @param primaryKey the primary key of this j7z3 entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the j7z3 entry ID of this j7z3 entry.
	 *
	 * @return the j7z3 entry ID of this j7z3 entry
	 */
	public long getJ7z3EntryId();

	/**
	 * Sets the j7z3 entry ID of this j7z3 entry.
	 *
	 * @param j7z3EntryId the j7z3 entry ID of this j7z3 entry
	 */
	public void setJ7z3EntryId(long j7z3EntryId);

	/**
	 * Returns the name of this j7z3 entry.
	 *
	 * @return the name of this j7z3 entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this j7z3 entry.
	 *
	 * @param name the name of this j7z3 entry
	 */
	public void setName(String name);

	@Override
	public J7Z3Entry cloneWithOriginalValues();

}