/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.t2p5.model.impl;

import com.acme.t2p5.model.T2P5Entry;
import com.acme.t2p5.service.T2P5EntryLocalServiceUtil;

/**
 * The extended model base implementation for the T2P5Entry service. Represents a row in the &quot;T2P5_T2P5Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T2P5EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T2P5EntryImpl
 * @see T2P5Entry
 * @generated
 */
public abstract class T2P5EntryBaseImpl
	extends T2P5EntryModelImpl implements T2P5Entry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t2p5 entry model instance should use the <code>T2P5Entry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			T2P5EntryLocalServiceUtil.addT2P5Entry(this);
		}
		else {
			T2P5EntryLocalServiceUtil.updateT2P5Entry(this);
		}
	}

}