/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.s5e6.model.impl;

import com.acme.s5e6.model.S5E6Entry;
import com.acme.s5e6.service.S5E6EntryLocalServiceUtil;

/**
 * The extended model base implementation for the S5E6Entry service. Represents a row in the &quot;S5E6_S5E6Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link S5E6EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see S5E6EntryImpl
 * @see S5E6Entry
 * @generated
 */
public abstract class S5E6EntryBaseImpl
	extends S5E6EntryModelImpl implements S5E6Entry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s5e6 entry model instance should use the <code>S5E6Entry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			S5E6EntryLocalServiceUtil.addS5E6Entry(this);
		}
		else {
			S5E6EntryLocalServiceUtil.updateS5E6Entry(this);
		}
	}

}