/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.s5e6.model.impl;

import com.acme.s5e6.model.S5E6Entry;
import com.acme.s5e6.model.S5E6EntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the S5E6Entry service. Represents a row in the &quot;S5E6_S5E6Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>S5E6EntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link S5E6EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see S5E6EntryImpl
 * @generated
 */
public class S5E6EntryModelImpl
	extends BaseModelImpl<S5E6Entry> implements S5E6EntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s5e6 entry model instance should use the <code>S5E6Entry</code> interface instead.
	 */
	public static final String TABLE_NAME = "S5E6_S5E6Entry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"S5E6EntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"description", Types.VARCHAR}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("S5E6EntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table S5E6_S5E6Entry (uuid_ VARCHAR(75) null,S5E6EntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,description VARCHAR(75) null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table S5E6_S5E6Entry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY s5e6Entry.S5E6EntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY S5E6_S5E6Entry.S5E6EntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long S5E6ENTRYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public S5E6EntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _S5E6EntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setS5E6EntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _S5E6EntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return S5E6Entry.class;
	}

	@Override
	public String getModelClassName() {
		return S5E6Entry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<S5E6Entry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<S5E6Entry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<S5E6Entry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((S5E6Entry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<S5E6Entry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<S5E6Entry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(S5E6Entry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<S5E6Entry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<S5E6Entry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, S5E6Entry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			S5E6Entry.class.getClassLoader(), S5E6Entry.class,
			ModelWrapper.class);

		try {
			Constructor<S5E6Entry> constructor =
				(Constructor<S5E6Entry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<S5E6Entry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<S5E6Entry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<S5E6Entry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<S5E6Entry, Object>>();
		Map<String, BiConsumer<S5E6Entry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<S5E6Entry, ?>>();

		attributeGetterFunctions.put("uuid", S5E6Entry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<S5E6Entry, String>)S5E6Entry::setUuid);
		attributeGetterFunctions.put("S5E6EntryId", S5E6Entry::getS5E6EntryId);
		attributeSetterBiConsumers.put(
			"S5E6EntryId",
			(BiConsumer<S5E6Entry, Long>)S5E6Entry::setS5E6EntryId);
		attributeGetterFunctions.put("groupId", S5E6Entry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<S5E6Entry, Long>)S5E6Entry::setGroupId);
		attributeGetterFunctions.put("companyId", S5E6Entry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<S5E6Entry, Long>)S5E6Entry::setCompanyId);
		attributeGetterFunctions.put("userId", S5E6Entry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<S5E6Entry, Long>)S5E6Entry::setUserId);
		attributeGetterFunctions.put("userName", S5E6Entry::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<S5E6Entry, String>)S5E6Entry::setUserName);
		attributeGetterFunctions.put("createDate", S5E6Entry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<S5E6Entry, Date>)S5E6Entry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", S5E6Entry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<S5E6Entry, Date>)S5E6Entry::setModifiedDate);
		attributeGetterFunctions.put("description", S5E6Entry::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<S5E6Entry, String>)S5E6Entry::setDescription);
		attributeGetterFunctions.put("name", S5E6Entry::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<S5E6Entry, String>)S5E6Entry::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getS5E6EntryId() {
		return _S5E6EntryId;
	}

	@Override
	public void setS5E6EntryId(long S5E6EntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_S5E6EntryId = S5E6EntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(S5E6Entry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), S5E6Entry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public S5E6Entry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, S5E6Entry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		S5E6EntryImpl s5e6EntryImpl = new S5E6EntryImpl();

		s5e6EntryImpl.setUuid(getUuid());
		s5e6EntryImpl.setS5E6EntryId(getS5E6EntryId());
		s5e6EntryImpl.setGroupId(getGroupId());
		s5e6EntryImpl.setCompanyId(getCompanyId());
		s5e6EntryImpl.setUserId(getUserId());
		s5e6EntryImpl.setUserName(getUserName());
		s5e6EntryImpl.setCreateDate(getCreateDate());
		s5e6EntryImpl.setModifiedDate(getModifiedDate());
		s5e6EntryImpl.setDescription(getDescription());
		s5e6EntryImpl.setName(getName());

		s5e6EntryImpl.resetOriginalValues();

		return s5e6EntryImpl;
	}

	@Override
	public S5E6Entry cloneWithOriginalValues() {
		S5E6EntryImpl s5e6EntryImpl = new S5E6EntryImpl();

		s5e6EntryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		s5e6EntryImpl.setS5E6EntryId(
			this.<Long>getColumnOriginalValue("S5E6EntryId"));
		s5e6EntryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		s5e6EntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		s5e6EntryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		s5e6EntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		s5e6EntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		s5e6EntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		s5e6EntryImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		s5e6EntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return s5e6EntryImpl;
	}

	@Override
	public int compareTo(S5E6Entry s5e6Entry) {
		long primaryKey = s5e6Entry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof S5E6Entry)) {
			return false;
		}

		S5E6Entry s5e6Entry = (S5E6Entry)object;

		long primaryKey = s5e6Entry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<S5E6Entry> toCacheModel() {
		S5E6EntryCacheModel s5e6EntryCacheModel = new S5E6EntryCacheModel();

		s5e6EntryCacheModel.uuid = getUuid();

		String uuid = s5e6EntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			s5e6EntryCacheModel.uuid = null;
		}

		s5e6EntryCacheModel.S5E6EntryId = getS5E6EntryId();

		s5e6EntryCacheModel.groupId = getGroupId();

		s5e6EntryCacheModel.companyId = getCompanyId();

		s5e6EntryCacheModel.userId = getUserId();

		s5e6EntryCacheModel.userName = getUserName();

		String userName = s5e6EntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			s5e6EntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			s5e6EntryCacheModel.createDate = createDate.getTime();
		}
		else {
			s5e6EntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			s5e6EntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			s5e6EntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		s5e6EntryCacheModel.description = getDescription();

		String description = s5e6EntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			s5e6EntryCacheModel.description = null;
		}

		s5e6EntryCacheModel.name = getName();

		String name = s5e6EntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			s5e6EntryCacheModel.name = null;
		}

		return s5e6EntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<S5E6Entry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<S5E6Entry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<S5E6Entry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((S5E6Entry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<S5E6Entry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<S5E6Entry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<S5E6Entry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((S5E6Entry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, S5E6Entry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _S5E6EntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _description;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<S5E6Entry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((S5E6Entry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("S5E6EntryId", _S5E6EntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("name", _name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("S5E6EntryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("description", 256L);

		columnBitmasks.put("name", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private S5E6Entry _escapedModel;

}