/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.h6d2.model.impl;

import com.acme.h6d2.model.H6D2Entry;
import com.acme.h6d2.service.H6D2EntryLocalServiceUtil;

/**
 * The extended model base implementation for the H6D2Entry service. Represents a row in the &quot;H6D2_H6D2Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link H6D2EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see H6D2EntryImpl
 * @see H6D2Entry
 * @generated
 */
public abstract class H6D2EntryBaseImpl
	extends H6D2EntryModelImpl implements H6D2Entry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a h6d2 entry model instance should use the <code>H6D2Entry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			H6D2EntryLocalServiceUtil.addH6D2Entry(this);
		}
		else {
			H6D2EntryLocalServiceUtil.updateH6D2Entry(this);
		}
	}

}