/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.e4g5.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the E4G5Entry service. Represents a row in the &quot;E4G5_E4G5Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.acme.e4g5.model.impl.E4G5EntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.acme.e4g5.model.impl.E4G5EntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see E4G5Entry
 * @generated
 */
@ProviderType
public interface E4G5EntryModel extends BaseModel<E4G5Entry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e4g5 entry model instance should use the {@link E4G5Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this e4g5 entry.
	 *
	 * @return the primary key of this e4g5 entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e4g5 entry.
	 *
	 * @param primaryKey the primary key of this e4g5 entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the e4g5 entry ID of this e4g5 entry.
	 *
	 * @return the e4g5 entry ID of this e4g5 entry
	 */
	public long getE4g5EntryId();

	/**
	 * Sets the e4g5 entry ID of this e4g5 entry.
	 *
	 * @param e4g5EntryId the e4g5 entry ID of this e4g5 entry
	 */
	public void setE4g5EntryId(long e4g5EntryId);

	/**
	 * Returns the description of this e4g5 entry.
	 *
	 * @return the description of this e4g5 entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e4g5 entry.
	 *
	 * @param description the description of this e4g5 entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this e4g5 entry.
	 *
	 * @return the name of this e4g5 entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e4g5 entry.
	 *
	 * @param name the name of this e4g5 entry
	 */
	public void setName(String name);

	@Override
	public E4G5Entry cloneWithOriginalValues();

}