rm h6d2-api/src/main/java/com/acme/h6d2/exception/NoSuchH6D2Exception.java
rm h6d2-api/src/main/java/com/acme/h6d2/model/H6D2.java
rm h6d2-api/src/main/java/com/acme/h6d2/model/H6D2Model.java
rm h6d2-api/src/main/java/com/acme/h6d2/model/H6D2Soap.java
rm h6d2-api/src/main/java/com/acme/h6d2/model/H6D2Table.java
rm h6d2-api/src/main/java/com/acme/h6d2/model/H6D2Wrapper.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/H6D2LocalService.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/H6D2LocalServiceUtil.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/H6D2LocalServiceWrapper.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/H6D2Service.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/H6D2ServiceUtil.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/H6D2ServiceWrapper.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/persistence/H6D2Persistence.java
rm h6d2-api/src/main/java/com/acme/h6d2/service/persistence/H6D2Util.java
rm h6d2-service/src/main/java/com/acme/h6d2/model/impl/H6D2BaseImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/model/impl/H6D2CacheModel.java
rm h6d2-service/src/main/java/com/acme/h6d2/model/impl/H6D2Impl.java
rm h6d2-service/src/main/java/com/acme/h6d2/model/impl/H6D2ModelImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/base/H6D2LocalServiceBaseImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/base/H6D2ServiceBaseImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/http/H6D2ServiceHttp.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/http/H6D2ServiceSoap.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/impl/H6D2LocalServiceImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/impl/H6D2ServiceImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/persistence/impl/H6D2PersistenceImpl.java
rm h6d2-service/src/main/java/com/acme/h6d2/service/persistence/impl/constants/H6D2PersistenceConstants.java
rm h6d2-uad/src/main/java/com/acme/h6d2/uad/anonymizer/BaseH6D2UADAnonymizer.java
rm h6d2-uad/src/main/java/com/acme/h6d2/uad/anonymizer/H6D2UADAnonymizer.java
rm h6d2-uad/src/main/java/com/acme/h6d2/uad/display/BaseH6D2UADDisplay.java
rm h6d2-uad/src/main/java/com/acme/h6d2/uad/display/H6D2UADDisplay.java
rm h6d2-uad/src/main/java/com/acme/h6d2/uad/exporter/BaseH6D2UADExporter.java
rm h6d2-uad/src/main/java/com/acme/h6d2/uad/exporter/H6D2UADExporter.java
