/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.h6d2.uad.display;

import com.acme.h6d2.model.Todo;
import com.acme.h6d2.service.TodoLocalService;
import com.acme.h6d2.uad.constants.H6D2UADConstants;

import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.user.associated.data.display.BaseModelUADDisplay;

import java.io.Serializable;

import java.util.List;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Todo UAD display.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom methods should be put in
 * {@link TodoUADDisplay}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseTodoUADDisplay extends BaseModelUADDisplay<Todo> {

	@Override
	public Todo get(Serializable primaryKey) throws PortalException {
		return todoLocalService.getTodo(Long.valueOf(primaryKey.toString()));
	}

	@Override
	public String[] getDisplayFieldNames() {
		return new String[] {"name"};
	}

	@Override
	public Class<Todo> getTypeClass() {
		return Todo.class;
	}

	@Override
	protected long doCount(DynamicQuery dynamicQuery) {
		return todoLocalService.dynamicQueryCount(dynamicQuery);
	}

	@Override
	protected DynamicQuery doGetDynamicQuery() {
		return todoLocalService.dynamicQuery();
	}

	@Override
	protected List<Todo> doGetRange(
		DynamicQuery dynamicQuery, int start, int end) {

		return todoLocalService.dynamicQuery(dynamicQuery, start, end);
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return H6D2UADConstants.USER_ID_FIELD_NAMES_TODO;
	}

	@Reference
	protected TodoLocalService todoLocalService;

}