/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.w9b7.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the W9B7Entry service. Represents a row in the &quot;W9B7_W9B7Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.acme.w9b7.model.impl.W9B7EntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.acme.w9b7.model.impl.W9B7EntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see W9B7Entry
 * @generated
 */
@ProviderType
public interface W9B7EntryModel extends BaseModel<W9B7Entry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w9b7 entry model instance should use the {@link W9B7Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this w9b7 entry.
	 *
	 * @return the primary key of this w9b7 entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w9b7 entry.
	 *
	 * @param primaryKey the primary key of this w9b7 entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the w9b7 entry ID of this w9b7 entry.
	 *
	 * @return the w9b7 entry ID of this w9b7 entry
	 */
	public long getW9b7EntryId();

	/**
	 * Sets the w9b7 entry ID of this w9b7 entry.
	 *
	 * @param w9b7EntryId the w9b7 entry ID of this w9b7 entry
	 */
	public void setW9b7EntryId(long w9b7EntryId);

	/**
	 * Returns the description of this w9b7 entry.
	 *
	 * @return the description of this w9b7 entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this w9b7 entry.
	 *
	 * @param description the description of this w9b7 entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this w9b7 entry.
	 *
	 * @return the name of this w9b7 entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this w9b7 entry.
	 *
	 * @param name the name of this w9b7 entry
	 */
	public void setName(String name);

}