/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.h6d2.uad.exporter;

import com.acme.h6d2.model.Todo;
import com.acme.h6d2.service.TodoLocalService;
import com.acme.h6d2.uad.constants.H6D2UADConstants;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the todo UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link TodoUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseTodoUADExporter
	extends DynamicQueryUADExporter<Todo> {

	@Override
	public Class<Todo> getTypeClass() {
		return Todo.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return todoLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return H6D2UADConstants.USER_ID_FIELD_NAMES_TODO;
	}

	@Override
	protected String toXmlString(Todo todo) {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.acme.h6d2.model.Todo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>todoId</column-name><column-value><![CDATA[");
		sb.append(todo.getTodoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(todo.getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(todo.getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(todo.getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected TodoLocalService todoLocalService;

}