/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.h6d2.uad.anonymizer;

import com.acme.h6d2.model.H6D2;
import com.acme.h6d2.service.H6D2LocalService;
import com.acme.h6d2.uad.constants.H6D2UADConstants;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the h6d2 UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link H6D2UADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseH6D2UADAnonymizer
	extends DynamicQueryUADAnonymizer<H6D2> {

	@Override
	public void autoAnonymize(H6D2 h6d2, long userId, User anonymousUser)
		throws PortalException {

		if (h6d2.getUserId() == userId) {
			h6d2.setUserId(anonymousUser.getUserId());
			h6d2.setUserName(anonymousUser.getFullName());
		}

		h6d2LocalService.updateH6D2(h6d2);
	}

	@Override
	public void delete(H6D2 h6d2) throws PortalException {
		h6d2LocalService.deleteH6D2(h6d2);
	}

	@Override
	public Class<H6D2> getTypeClass() {
		return H6D2.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return h6d2LocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return H6D2UADConstants.USER_ID_FIELD_NAMES_H6D2;
	}

	@Reference
	protected H6D2LocalService h6d2LocalService;

}