/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.h6d2.uad.anonymizer;

import com.acme.h6d2.model.Todo;
import com.acme.h6d2.service.TodoLocalService;
import com.acme.h6d2.uad.constants.H6D2UADConstants;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the todo UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link TodoUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseTodoUADAnonymizer
	extends DynamicQueryUADAnonymizer<Todo> {

	@Override
	public void autoAnonymize(Todo todo, long userId, User anonymousUser)
		throws PortalException {

		if (todo.getUserId() == userId) {
			todo.setUserId(anonymousUser.getUserId());
			todo.setUserName(anonymousUser.getFullName());
		}

		todoLocalService.updateTodo(todo);
	}

	@Override
	public void delete(Todo todo) throws PortalException {
		todoLocalService.deleteTodo(todo);
	}

	@Override
	public Class<Todo> getTypeClass() {
		return Todo.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return todoLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return H6D2UADConstants.USER_ID_FIELD_NAMES_TODO;
	}

	@Reference
	protected TodoLocalService todoLocalService;

}