/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.j7z3.model.impl;

import com.acme.j7z3.model.J7Z3Entry;
import com.acme.j7z3.service.J7Z3EntryLocalServiceUtil;

/**
 * The extended model base implementation for the J7Z3Entry service. Represents a row in the &quot;J7Z3_J7Z3Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link J7Z3EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see J7Z3EntryImpl
 * @see J7Z3Entry
 * @generated
 */
public abstract class J7Z3EntryBaseImpl
	extends J7Z3EntryModelImpl implements J7Z3Entry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a j7z3 entry model instance should use the <code>J7Z3Entry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			J7Z3EntryLocalServiceUtil.addJ7Z3Entry(this);
		}
		else {
			J7Z3EntryLocalServiceUtil.updateJ7Z3Entry(this);
		}
	}

}